### ISSUE TITLE
Getting GraphQL.ExecutionError when trying to access the endpoint

### ISSUE THREAD

**Issue by atresnjo** [WiredUK/Graphity#1]
Hi,

First of all, thank you for the library as I wanted to write one myself after a painful experience with ef core and graphql; so you saved me a lot of time! I followed your instructions and I'm getting the following error once I try to access the endpoint using GraphiQL, the exception throws without executing a query. Just switching the GraphiQL tab which executes the schema request I assume. Thanks!

![grafik](https://user-images.githubusercontent.com/41112852/50738739-bf802d00-11d7-11e9-8291-43944a4c713e.png)

**Comment by WiredUK** [comment]
Thanks for trying this out, it's really great when I get feedback.

For your problem, that was because I hadn't considered people using the Guid type - a big oops from me! I've added that support in now and pushed a new Nuget package. The package is currently validating but should be ready in a few minutes at https://www.nuget.org/packages/Graphity/1.0.1

I'll leave this issue open until you confirm that has fixed the problem or if I need to to more work!

**Comment by atresnjo** [comment]
> 
> 
> Thanks for trying this out, it's really great when I get feedback.
> 
> For your problem, that was because I hadn't considered people using the Guid type - a big oops from me! I've added that support in now and pushed a new Nuget package. The package is currently validating but should be ready in a few minutes at https://www.nuget.org/packages/Graphity/1.0.1
> 
> I'll leave this issue open until you confirm that has fixed the problem or if I need to to more work!

That update fixed the exception, now I'm getting another one. ManagerType is an Enum. Thanks for the quick update! 👍 

![grafik](https://user-images.githubusercontent.com/41112852/50740182-12afab00-11eb-11e9-8a73-ff21d45a1ccb.png)

**Comment by WiredUK** [comment]
Ahhhh nullable enums! Seems my code for coping with them was broken. I've fixed that now if you want to try [v1.0.2](https://www.nuget.org/packages/Graphity/1.0.2)!

**Comment by atresnjo** [comment]
> 
> 
> Ahhhh nullable enums! Seems my code for coping with them was broken. I've fixed that now if you want to try [v1.0.2](https://www.nuget.org/packages/Graphity/1.0.2). Thanks for your patience.

We are getting closer! 👍 EmployeeRole is also an Enum

![grafik](https://user-images.githubusercontent.com/41112852/50741040-5fe64980-11f8-11e9-8885-9133d977e843.png)

**Comment by atresnjo** [comment]
> 
> 
> Hmm that is peculiar as enums work well, I've even added a test to confirm it. It's just a plain enum, nothing special about it? Does the entity property have anything interesting defined against it?

Yep, nothing special.

![grafik](https://user-images.githubusercontent.com/41112852/50741199-23b3e880-11fa-11e9-83d9-df48f7482247.png)

It's used in one entity class just as a normal property.

![grafik](https://user-images.githubusercontent.com/41112852/50741240-9de46d00-11fa-11e9-8de2-61af36b499cb.png)

**Comment by WiredUK** [comment]
I managed to repro this in my code too. I've tweaked how the enums are done slightly and hopefully v1.0.3 will help.

**Comment by atresnjo** [comment]
> 
> 
> I managed to repro this in my code too. I've tweaked how the enums are done slightly and hopefully v1.0.3 will help.

Yep, that fixed it. Now I'm having another type fail. It's a class for a join table.

![grafik](https://user-images.githubusercontent.com/41112852/50742066-975bf280-1206-11e9-9188-9fd84209c2bf.png)


![grafik](https://user-images.githubusercontent.com/41112852/50742032-2c122080-1206-11e9-9768-4b4ed51c39e9.png)

**Comment by WiredUK** [comment]
I'm guessing that you haven't defined a `DbSet<ScopePermission>` in your `DbContext`? That might cause this issue.
