### ISSUE TITLE
Entities with byte properties aren't getting registered. 

### ISSUE THREAD

**Issue by cdarrigo** [WiredUK/Graphity#3]
My DBContext contains an entity with a byte property. 

`public class MyEntity
{
  public byte Size {get;set;}
}`

After registering the services, when I try to hit the api/graph endpoint I get the following error:

GraphQL.ExecutionError: No service for type 'Graphity.DynamicObjectGraphType`2[MyDataContext,System.Byte]' has been registered.

**Comment by WiredUK** [comment]
I've pushed an update that should fix it, can you try the [latest Nuget package](https://www.nuget.org/packages/Graphity/1.0.5) please?
Now I need to fix the tests as I thought it might be a good idea to migrate to .NET 5 at the same time. It wasn't!

**Comment by WiredUK** [comment]
I was wondering if you had a chance to try this out so I can close this issue?
